### ISSUE TITLE
Crash when trying to add genomic mutations for VHL

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/cancermuts#163]
Traceback:

```
Traceback (most recent call last):
  File "pancancer_clinvar.py", line 33, in <module>
    mv.add_metadata(seq)
  File "/usr/local/envs/cancermuts/lib/python3.8/site-packages/cancermuts/datasources.py", line 848, in add_metadata
    add_this_metadata(mut)
  File "/usr/local/envs/cancermuts/lib/python3.8/site-packages/cancermuts/datasources.py", line 878, in _get_revel
    revel_score = self._get_revel_from_gm(mutation, gm)
  File "/usr/local/envs/cancermuts/lib/python3.8/site-packages/cancermuts/datasources.py", line 954, in _get_revel_from_gm
    if not gm.is_snv:
AttributeError: 'GenomicMutation' object has no attribute 'is_snv'
```

**Comment by elenapapaleo** [comment]
this is solved now
