### ISSUE TITLE
Crash when plotting metatable

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/cancermuts#165]
For instance, when running on VHL:

```
Metadata columns not found in csv file (these are: genomic_mutations).
property structure not found in data; it won't be annotated
MPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEMEAGRPRPVLRSVNSREPSQVIFCNRSPRVVLPVWLNFDGEPQPYPTLPPGTGRRIHSYRGHLWLFRDAGTHDGLLVNQTELFVPSLNVDGQPIFANITLPVYTLKERCLQVVRSLVKPENYRRLDIVRSLYEDLEDHPNVQKDLERLTQERIAHQRMGD
Traceback (most recent call last):
  File "pancancer_clinvar.py", line 69, in <module>
    ax, fig = tbl.plot_metatable(df, fname='plot_metatable.pdf', section_size=20, figsize=(15,100))
  File "/data/user/teo/devel/cancermuts/cancermuts/table.py", line 600, in plot_metatable
    self._plot_elms(ax, df, df_i, mutation_elms_only=mutation_elms_only, y_ladder=elm_y_ladder)
  File "/data/user/teo/devel/cancermuts/cancermuts/table.py", line 423, in _plot_elms
    all_elms[i][1] = [ int(e) for e in elm[1].split('-') ]
IndexError: list index out of range
```

**Comment by mtiberti** [comment]
this is a regression from #161 - we didn't modify the plotting code according to the new format in the metatable
