### ISSUE TITLE
Crash when doing ELM predictions

### ISSUE THREAD

**Issue by katmeld** [ELELAB/cancermuts#167]
When doing `ELMPredictions().add_sequence_properties(seq)` it crashes. Works fine with this command `elm.add_sequence_properties(seq,exclude_elm_classes="MOD_.")`

```
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    elm.add_sequence_properties(seq)
  File "/data/user/kame/devel/cancermuts/cancermuts/cancermuts/datasources.py", line 1143, in add_sequence_properties
    if re.match(exclude_elm_classes, d[0]):
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/sre_parse.py", line 645, in _parse
    source.tell() - here + len(this))


re.error: nothing to repeat at position 0

**Comment by katmeld** [comment]
In line 1130 where `add_sequence_properties` is defined, the following is the default.

```exclude_elm_classes='{100}'```

As far as I can gather, you can start the regex with {100} ([source](https://stackoverflow.com/questions/31386552/nothing-to-repeat-from-python-regex)). 

And what exactly should the default be/do?
