### ISSUE TITLE
COSMIC() crashes when no file is specified

### ISSUE THREAD

**Issue by katmeld** [ELELAB/cancermuts#169]
In this case, I think the default path is just outdated, but it would be nice to not crash like this

```Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    cs=COSMIC()
  File "/data/user/kame/devel/cancermuts/cancermuts/cancermuts/log.py", line 50, in wrapper
    function(*args, **kwargs)
  File "/data/user/kame/devel/cancermuts/cancermuts/cancermuts/datasources.py", line 546, in __init__
    dataframes.append( pd.read_csv(f, sep='\t', dtype='str', na_values='NS', usecols=self._use_cols_snp, encoding=encodings[fi]) )
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/data/user/kame/devel/cancermuts/cancermuts_env/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",

FileNotFoundError: [Errno 2] No such file or directory: '/data/databases/cosmic/CosmicMutantExport.tsv'

**Comment by mtiberti** [comment]
hi, agreed. Tbh I think there should be no default path for the files, that should just become a mandatory argument
