### ISSUE TITLE
Assertion in genomic coordinate conversion makes cancermuts crash

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/cancermuts#201]
when pulling REVEL scores, a conversion from hg38 to hg19 is attempted - liftOver might occasionally fail, which in triggers an assertion in our code:

```
Traceback (most recent call last):
  File "pancancer.py", line 66, in <module>
    mv.add_metadata(seq)
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 889, in add_metadata
    add_this_metadata(mut)
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 919, in _get_revel
    revel_scores = self._get_revel_from_gm(mutation, gm)
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 1003, in _get_revel_from_gm
    converted_coords = self._convert_hg38_to_hg19(gm)
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 989, in _convert_hg38_to_hg19
    assert len(converted_coords) == 1
AssertionError
```

rather than having an assertion we should just handle these cases

**Comment by mtiberti** [comment]
similar issues also rise using the `GenomicCoordinates` conversion:

```
Traceback (most recent call last):
  File "pancancer.py", line 70, in <module>
    gnomad.add_metadata(seq, md_type=['gnomad_exome_allele_frequency',
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 1416, in add_metadata
    add_this_metadata(mut, gene_id)
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 1420, in _get_exome_allele_freq
    self._get_metadata(mutation, gene_id, 'gnomad_exome_allele_frequency')
  File "/data/user/teo/devel/cancermuts/cancermuts/datasources.py", line 1502, in _get_metadata
    v_str = variant.as_assembly(ref_assembly).get_value_str(fmt='gnomad')
  File "/data/user/teo/devel/cancermuts/cancermuts/metadata.py", line 256, in as_assembly
    return self.as_hg19()
  File "/data/user/teo/devel/cancermuts/cancermuts/metadata.py", line 226, in as_hg19
    assert len(converted_coords) == 1
AssertionError
```
